# Generated by Django 6.0 on 2026-01-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('file', models.FileField(upload_to='programas/')),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('iframe', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
