# Generated by Django 6.0 on 2026-01-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='file',
            field=models.FileField(upload_to='apps/'),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
