# Generated by Django 6.0 on 2026-01-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appmodel_file_alter_appmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodel',
            name='hook',
            field=models.TextField(default='pendiente', max_length=80),
            preserve_default=False,
        ),
    ]
